### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by chenjinhao** [jiangxy/react-java-goos#1]
你好！我是一个java后端，最近参考使用你的这套方案，这种方式非常棒，但是我想问下，你能贴下你的java后端结构吗，因为你生成的文件中，是每个表独立文件夹的，和我原来的习惯不太一样。

**Comment by chenjinhao** [comment]
另外，如果我不使用lombok的话，删掉相关的内容应该没有关系吧？

**Comment by jiangxy** [comment]
@chenjinhao 不使用lombok  完全没有问题    只是要自己写getter/setter了
我的java后端    其实就是一个普通的SpringMVC的工程    没什么特殊的结构  
生成的java类    可以按自己心情拷到对应的package中的😄

**Comment by chenjinhao** [comment]
@jiangxy 多谢回复！另外还有一个问题，权限控制怎么在前端工程中隐藏路径

**Comment by jiangxy** [comment]
@chenjinhao 不是很明白你的意思   “在前端工程中隐藏路径”指的是？

**Comment by chenjinhao** [comment]
@jiangxy 就是业务人员只能查看自己的权限目录，看不到全部路径的。

**Comment by jiangxy** [comment]
@chenjinhao 哦，这个目前还没有考虑权限问题😓
前端现在没有什么权限控制的机制，可以在后端接口上限制
我们用了比较土的做法，后端日志记录每个操作的人员，有问题事后追责😓

**Comment by chenjinhao** [comment]
@jiangxy 哦哦，好吧，我再看看
